### ISSUE TITLE
Write about powermock and Jenkins

### ISSUE THREAD

**Issue by kinow** [kinow/kinoshita.eti.br#9]
```
WARNING: Failed to instantiate Key[type=hudson.security.csrf.DefaultCrumbIssuer$DescriptorImpl, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.ClassCastException: com.sun.crypto.provider.AESCipher cannot be cast to javax.crypto.CipherSpi
  at hudson.security.csrf.DefaultCrumbIssuer$DescriptorImpl.<init>(DefaultCrumbIssuer.java:127)

1 error
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
```

https://github.com/jayway/powermock/issues/294

Already updated Jenkins Wiki: https://wiki.jenkins-ci.org/display/JENKINS/Mocking+in+Unit+Tests

**Comment by kinow** [comment]
Done!
